name: Deployment

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node and NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.0

            - name: Install NPM Packages
              run: npm ci

            - name: Compile
              run: npm run make

            - name: Load SSH Key
              uses: webfactory/ssh-agent@v0.4.1
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Pre Deployment
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSH_KEY }}
                  script: sudo chown -R $USER:$USER ~/server

            - name: Deploy
              run: rsync -azh --delete-after --exclude={'./.env','./.github/','./.gitignore','./tsconfig.json','./package.json','./package-lock.json','./src/','./build/'} -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/server

            - name: Post Deployment
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSH_KEY }}
                  script: /home/${{ secrets.USERNAME }}/.nvm/versions/node/v16.14.0/bin/pm2 restart 0

            - name: Purge cache
              uses: nathanvaughn/actions-cloudflare-purge@master
              if: success()
              with:
                  cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
                  cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
